### ISSUE TITLE
Setting mode to AP not remembered

### ISSUE THREAD

**Issue by mi-kal** [jeelabs/esp-link#101]
After a reset, WiFi is back in STA+AP mode even if set to AP-only in web interface. Keeps running "Wifi checks" without SSID.

**Comment by stockklauser** [comment]
+1

**Comment by tve** [comment]
This is with 2.0.beta1 I assume?

**Comment by tve** [comment]
Note that esp-link will not stay in AP+STA mode after reset, but it now will stay in AP-only mode after a reset.
