### ISSUE TITLE
New esp-open-sdk release

### ISSUE THREAD

**Issue by apwiede** [jeelabs/esp-link#113]
- there seems to be a new release 1.5.2 of esp-open-sdk, I had to adapt the Makefile.
- there seem to be stronger syntax checks, I had to cast the 3rd parameter of getBoolArg:
  (bool *)(&flashConfig.......)

**Comment by derSascha** [comment]
@apwiede thanks for the hint!

**Comment by deece** [comment]
Casting to bool \* is not advisable as bool is not guaranteed to be a single byte (and is typically an int).

Here's a different way to fix it.

**Comment by deece** [comment]
Also relates to #75

bool used to be typedef'd to unsigned char (which was why no warnings were produced), but now comes from stdbool.h.

See c_types-c99.patch in the SDK.

**Comment by deece** [comment]
Some more errors (mostly format warnings coereced to errors):
mqtt/mqtt_cmd.c: In function 'cmdMqttDataCb':
mqtt/mqtt_cmd.c:45:3: error: format '%ld' expects argument of type 'long int', but argument 4 has type 'uint32_t' [-Werror=format=]
   DBG("MQTT: Data cb=%p topic=%s len=%ld\n", (void*)cb->dataCb, topic, data_len);
   ^
mqtt/mqtt_cmd.c: In function 'MQTTCMD_Subscribe':
mqtt/mqtt_cmd.c:171:3: error: format '%ld' expects argument of type 'long int', but argument 3 has type 'uint32_t' [-Werror=format=]
   DBG("MQTT: MQTTCMD_Subscribe topic=%s, qos=%ld\n", topic, qos);
   ^
mqtt/mqtt_cmd.c: In function 'MQTTCMD_Setup':
mqtt/mqtt_cmd.c:248:3: error: format '%lx' expects argument of type 'long unsigned int', but argument 2 has type 'uint32_t' [-Werror=format=]
   DBG("MQTT connectedCb=%lx\n", callback->connectedCb);

rest/rest.c: In function 'REST_Setup':
rest/rest.c:255:3: error: format '%ld' expects argument of type 'long int', but argument 4 has type 'uint32_t' [-Werror=format=]
   DBG_REST("REST: setup #%d host=%s port=%ld security=%ld\n", clientNum, rest_host, port, security);
   ^
rest/rest.c:255:3: error: format '%ld' expects argument of type 'long int', but argument 5 has type 'uint32_t' [-Werror=format=]
rest/rest.c: In function 'REST_Request':
rest/rest.c:351:3: error: format '%ld' expects argument of type 'long int', but argument 2 has type 'uint32_t' [-Werror=format=]
   DBG_REST(" #%ld", clientNum);
   ^
rest/rest.c:377:3: error: format '%ld' expects argument of type 'long int', but argument 2 has type 'uint32_t' [-Werror=format=]
   DBG_REST(" bodyLen=%ld", realLen);
   ^
rest/rest.c:396:3: error: format '%ld' expects argument of type 'long int', but argument 2 has type 'uint32_t' [-Werror=format=]
   DBG_REST(" totLen=%ld data=%p", headerLen + realLen, client->data);
   ^
rest/rest.c:415:5: error: format '%ld' expects argument of type 'long int', but argument 3 has type 'uint32_t' [-Werror=format=]
     DBG_REST("REST: Connect to ip %s:%ld\n",client->host, client->port);
     ^
rest/rest.c:423:5: error: format '%ld' expects argument of type 'long int', but argument 3 has type 'uint32_t' [-Werror=format=]
     DBG_REST("REST: Connect to host %s:%ld\n", client->host, client->port);

syslog/syslog.c: In function 'syslog_compose':
syslog/syslog.c:409:7: error: format '%lu' expects argument of type 'long unsigned int', but argument 3 has type 'uint32_t' [-Werror=format=]
       p += os_sprintf(p, ".%06luZ ", se->tick % 1000000);
       ^
syslog/syslog.c:416:5: error: format '%lu' expects argument of type 'long unsigned int', but argument 5 has type 'uint32_t' [-Werror=format=]
     p += os_sprintf(p, "%s %s %lu.%06lu %lu ", flashConfig.hostname, tag, se->tick / 1000000, se->tick % 1000000, syslog_msgid++);
     ^
syslog/syslog.c:416:5: error: format '%lu' expects argument of type 'long unsigned int', but argument 6 has type 'uint32_t' [-Werror=format=]
syslog/syslog.c:416:5: error: format '%lu' expects argument of type 'long unsigned int', but argument 7 has type 'uint32_t' [-Werror=format=]
syslog/syslog.c:418:5: error: format '%lu' expects argument of type 'long unsigned int', but argument 5 has type 'uint32_t' [-Werror=format=]
     p += os_sprintf(p, "%s %s - %lu ", flashConfig.hostname, tag, syslog_msgid++);

serial/console.c:79:3: error: format '%ld' expects argument of type 'long int', but argument 3 has type 'int32_t' [-Werror=format=]
   os_sprintf(buff, "{\"rate\": %ld}", flashConfig.baud_rate);

cmd/handlers.c:65:7: error: format '%lx' expects argument of type 'long unsigned int', but argument 3 has type 'uint32_t' [-Werror=format=]
       DBG("cmdAddCb: '%s'->0x%lx added at %d\n", callbacks[i].name, cb, i);

cmd/cmd.c:46:3: error: format '%ld' expects argument of type 'long int', but argument 3 has type 'uint32_t' [-Werror=format=]
   DBG("cmdResponse: cmd=%d val=%ld argc=%d\n", cmd, value, argc);
   ^
cmd/cmd.c: In function 'cmdParsePacket':
cmd/cmd.c:110:3: error: format '%lu' expects argument of type 'long unsigned int', but argument 4 has type 'uint32_t' [-Werror=format=]
   DBG("cmdParsePacket: cmd=%d argc=%d value=%lu\n",

esp-link/cgiflash.c:33:3: error: format '%lX' expects argument of type 'long unsigned int', but argument 3 has type 'uint32_t' [-Werror=format=]
   os_printf("%p: %08lX %08lX %08lX %08lX\n", buf, buf32[0], buf32[1], buf32[2], buf32[3]);
   ^
esp-link/cgiflash.c:33:3: error: format '%lX' expects argument of type 'long unsigned int', but argument 4 has type 'uint32_t' [-Werror=format=]
esp-link/cgiflash.c:33:3: error: format '%lX' expects argument of type 'long unsigned int', but argument 5 has type 'uint32_t' [-Werror=format=]
esp-link/cgiflash.c:33:3: error: format '%lX' expects argument of type 'long unsigned int', but argument 6 has type 'uint32_t' [-Werror=format=]
esp-link/cgiservices.c:87:5: error: format '%lX' expects argument of type 'long unsigned int', but argument 7 has type 'uint32_t' [-Werror=format=]
     );
     ^
esp-link/cgiservices.c:87:5: error: format '%lX' expects argument of type 'long unsigned int', but argument 8 has type 'uint32_t' [-Werror=format=]
esp-link/cgiservices.c:87:5: error: format '%ld' expects argument of type 'long int', but argument 13 has type 'int32_t' [-Werror=format=]
esp-link/cgioptiboot.c:157:11: error: format '%ld' expects argument of type 'long int', but argument 3 has type 'uint32_t' [-Werror=format=]
           baudRate, optibootVers>>8, optibootVers&0xff);
           ^
esp-link/cgioptiboot.c: In function 'cgiOptibootData':
esp-link/cgioptiboot.c:319:9: error: format '%ld' expects argument of type 'long int', but argument 4 has type 'uint32_t' [-Werror=format=](int)(100.0_(10.0_pgmDone/baudRate)/dt));
         ^
esp-link/cgioptiboot.c: In function 'processRecord':
esp-link/cgioptiboot.c:390:5: error: format '%lx' expects argument of type 'long unsigned int', but argument 2 has type 'uint32_t' [-Werror=format=]
     DBG("OB address 0x%lx\n", getHexValue(buf+8, 4) << 16);
     ^
esp-link/cgioptiboot.c: In function 'programPage':
esp-link/cgioptiboot.c:438:3: error: format '%lx' expects argument of type 'long unsigned int', but argument 3 has type 'uint32_t' [-Werror=format=]
   DBG("OB pgm %d@0x%lx\n", pgmLen, optibootData->address);
   ^
esp-link/cgioptiboot.c: In function 'optibootTimerCB':
esp-link/cgioptiboot.c:528:7: error: format '%ld' expects argument of type 'long int', but argument 2 has type 'uint32_t' [-Werror=format=]
       DBG("OB no sync response @%ld baud\n", baudRate);
       ^
esp-link/cgioptiboot.c:543:11: error: format '%ld' expects argument of type 'long int', but argument 5 has type 'uint32_t' [-Werror=format=]
           progStates[progState], progState, baudRate);
esp-link/main.c:152:3: error: format '%lX' expects argument of type 'long unsigned int', but argument 3 has type 'uint32_t' [-Werror=format=]
   NOTICE("Flash map %s, manuf 0x%02lX chip 0x%04lX", flash_maps[system_get_flash_size_map()],
   ^
esp-link/main.c:152:3: error: format '%lX' expects argument of type 'long unsigned int', but argument 4 has type 'uint32_t' [-Werror=format=]

esp-link/cgipins.c:57:3: error: passing argument 3 of 'getBoolArg' from incompatible pointer type [-Werror]
   ok |= getBoolArg(connData, "swap", &swap);
   ^
esp-link/cgipins.c:58:3: error: passing argument 3 of 'getBoolArg' from incompatible pointer type [-Werror]
   ok |= getBoolArg(connData, "rxpup", &rxpup);
