### ISSUE TITLE
Configured device name should appear in html title

### ISSUE THREAD

**Issue by krahabors** [jeelabs/esp-link#116]
It would be nice if user-configured name showed up in a browser tab title. That would help to distinguish between several tabs with different esp-link devices.

**Comment by WheresWally** [comment]
Yep +1, I can see that in the future I will have that exact issue so a device name or configurable ID in the browser TAB title would be a big plus.

Probably use the Hostname set in System overview. It is used to set the name on the menu side bar at the moment.

**Comment by tve** [comment]
good idea, I'll see whether I can slip it into the next update.
