### ISSUE TITLE
Soft AP SSID minimum 8 characters?

### ISSUE THREAD

**Issue by jmcexx** [jeelabs/esp-link#126]
Using 2.2.beta2.  The configuration web page for Soft AP SSID does not allow the SSID to be less than 8 characters.  I'm guessing this is a bug in the web page code.

**Comment by tve** [comment]
The Wifi standard requires SSIDs to have at least 8 characters IIRC.

**Comment by martynj3** [comment]
Hi,

|
|

 - Martyn
 |

```
On Tuesday, March 22, 2016 3:19 PM, Thorsten von Eicken <notifications@github.com> wrote:
```

 The Wifi standard requires SSIDs to have at least 8 characters IIRC.—

**Comment by jmcexx** [comment]
I don't know about the standards, but all of my home routers allow short SSIDs.  Mine is only 3 characters right now.    

BTW, Thanks to you all for your work on this excellent project!

**Comment by tve** [comment]
mhh, looks indeed like there are some checks in there that shouldn't be there and I didn't catch when reviewing. Passwords are also limited to `\w*` which prevents punctuation characters, not good. Thanks for flagging this!

NB: the bad check is at https://github.com/jeelabs/esp-link/blob/master/esp-link/cgiwifi.c#L536 if you want to fix it and compile your own version. The invalid regular expression check for chars in password is at https://github.com/jeelabs/esp-link/blob/master/html/wifi/wifiAp.js#L31
