### ISSUE TITLE
attached uC reset multiple times at boot-up

### ISSUE THREAD

**Issue by tve** [jeelabs/esp-link#13]
Seen using esp-bridge and arduino

**Comment by JohnOH** [comment]
There is more to this powering up with a device connected. I mentioned the apparent multiple resets at power on of my JeeNode Block earlier. It transpires that I can typically only get a working TCP connection to it if I connect to the ESP after powering it up. If they are connected at ESP power on then nc 192.168.1.24 23 typically connects with no action - although there are exceptions where a "." or a "?" can get the RF12Demo menu working.
The upset appears to be in the JeeNode since hitting its reset button restores operation.

**Comment by JohnOH** [comment]
With a JeeNode connected to the ESP-Bridge the uC Console initially contains:
tion:
 A i1 g212 @ 868 MHz q1

> 0l
> 0s
>  -> 0 b
> 0l

Available commands:
   i     - set node ID (standard node ids are 1..30)
   b      - set MHz band (4 = 433, 8 = 868, 9 = 915)
   o   - change frequency offset within the band (default 1600)
               96..3903 is the range supported by the RFM12B
   g    - set network group (RFM12 only allows 212, 0 = any)
   c      - set collect mode (advanced, normally 0)
  t          - broadcast max-size test packet, request ack
  ..., a - send data packet to node , request ack
  ..., s - send data packet to node , no ack
   q      - set quiet mode (1 = don't report bad packets)

Interesting in that some commands appear to have been issued to the JeeNode: "lss" in one example. This varies as does the actual text captured from the initial RF12Demo menu.

After first connection is made there is no change in the uC Console.
After sending a "." towards the ESP-Bridge I a webpage comes back with changed text in the uC console box and above the yellow area containing "esp link - Microcontroller Console" is corrupted with random characters. Nothing has been delivered to the nc terminal.  
Device is responding to ping.
I think the webserver has gone absent.
ESP-Bridge yellow led is blinking, seeing characters I type into nc
When I browse to http://192.168.1.29 the URL is adjusted to http://192.168.1.29/index.tpl by something but:

No data received

ERR_EMPTY_RESPONSE

Using Google Chrome browser.
Reset JeeNode, nothing happening.
Detached and reattached JeeNode and still nothing happening.
JeeNode interface is at 115200.

**Comment by jcw** [comment]
is the uploaded sketch set to 115200 baud?

**Comment by JohnOH** [comment]
JeeNode interface is at 115200.

Well it was yesterday but not now - good spot @jcw.

**Comment by JohnOH** [comment]
Having corrected the JeeNode speed mistake the problem is in the main as before. The web server is sometimes corrupting the returned webpage and then going absent other times just going immediately absent.

**Comment by JohnOH** [comment]
esp-link - 0.9.4 - 2015-06-03 21:44:51 - c5eb65a

Is being overwhelmed by 115200. I will hold for a 0.9.5 version of ESP-Bridge.

**Comment by tve** [comment]
I verified that 0.10.3 no longer resets the attached uC if esp-link is reset
