### ISSUE TITLE
Does esp-link support client mode connect to TCP server?

### ISSUE THREAD

**Issue by ceremcem** [jeelabs/esp-link#135]
Is there any client mode supported like RM04's?

**Comment by KjellVerb** [comment]
Great question, I am looking for the same functionality. I would like the esp to open a specific port to an IP address on my LAN each time time that it starts up. The server is a RPi that is always on, but the esp is powered off more than on, so I don't want to open a new client connection each time.

**Comment by tve** [comment]
closing 'cause nothing has moved here in a very long time.

**Comment by sadransh** [comment]
is not there any way to do this?
