### ISSUE TITLE
Serial Port Conflicts, Is there anything of which to be careful?

### ISSUE THREAD

**Issue by WheresWally** [jeelabs/esp-link#136]
Is there a "gothca" when it comes to hooking the TX/RX to the RX/TX of a UNO?

Is there a chance that the TX from the USB Serial and the TX from the ESP-LINK will "fight"?
I would hate the magic smoke to be freed.

Can the Arduino be powered via the USB or should only the DC input be used when ESP-LINK is connected?

Terry

**Comment by tve** [comment]
Uno is 5v, so you need something to reduce the voltage of its TX to 3.3v. One option is a diode and a pull-up. You must connect TX to RX so nothing is "fighting"...
