### ISSUE TITLE
No more than 2-3 packets/sec from the ESP8266?

### ISSUE THREAD

**Issue by lucky01** [jeelabs/esp-link#143]
I read your post here
http://bbs.espressif.com/viewtopic.php?t=216
and have the same problem with the latest beta and SDK1.5.3.
Is RTOS version still faster or are there any other possibilities to
increase transfer speed ?

**Comment by tve** [comment]
I have not tested this stuff anytime recently, but I also haven't had issues. Sorry...

I'm going to close this ticker 'cause there's nothing actionable for me, feel free to reopen!
