### ISSUE TITLE
Longer MQTT server hostname

### ISSUE THREAD

**Issue by fedearne** [jeelabs/esp-link#147]
Please allow more than 31 characters in MQTT server hostname.

IBM Bluemix is free, but use rather long DNS aliases.

Thanks.
Morten

**Comment by PCcunha** [comment]
I am looking for this fix too. Looking at the code at config.h, if i increase the size of mqtt_host or any other field will break all configurations after that address, correct?

If i proceed that way, all updates will loose their configurations.

 What shoud be the correct fix for that issue?

**Comment by tve** [comment]
Yup, most likely the config version number needs to be bumped to avoid a mess, and ideally some migration code added that can take an old version and convert it by shifting up the bytes to make more room for the MQTT hostname.
