### ISSUE TITLE
Send hostname in DHCP request

### ISSUE THREAD

**Issue by tve** [jeelabs/esp-link#15]
To enable esp-link.local type of DNS names

**Comment by kd-2020** [comment]
Seconded, this would be convenient.

**Comment by tve** [comment]
This feature is dependent on the Espressif SDK's DHCP client implementation. The SDK version 1.1.2 supports setting the hostname, but it's not stable in other ways, specially scanning. So sadly I can't make this improvement yet...

**Comment by tve** [comment]
This is fixed as of release 0.10.0
