### ISSUE TITLE
make fails to build image

### ISSUE THREAD

**Issue by susisstrolch** [jeelabs/esp-link#159]
make (ef6a611) fails with following error message:

```
AR build/httpd_app.a
make: *** No rule to make target '/ld/eagle.app.v6.new.1024.app1.ld', needed by  build/eagle.esphttpd1.v6.ld'.  Stop.
```

**Comment by tve** [comment]
Sorry, cannot repro. This file is in $(SDK_LDDIR)/eagle.app.v6.new.1024.app1.ld, which SDK are you using?

**Comment by susisstrolch** [comment]
silly me... forgot to copy my local.mk...
