### ISSUE TITLE
Not really an issue but needs to be added to the documentation

### ISSUE THREAD

**Issue by SpaceCadet-Code** [jeelabs/esp-link#162]
Hey, I found that you can program an arduino over the esp using HWVSP which may be known but what I have not seen is the fact that nvt has to be unchecked in the HWVSP settings for it to work. Been trying to figure out what the heck was wrong for days then remembered that from phone flashing days.

**Comment by tve** [comment]
Cool. com2com works too. And there's a recent version of avrdude for windows that supports TCP ports. So there are lots of options...

**Comment by tve** [comment]
Added to docs, thanks!
