### ISSUE TITLE
Typical avrdude example in home.html has typo

### ISSUE THREAD

**Issue by bbx10** [jeelabs/esp-link#166]
On the esp-link home page, the -U option should be followed by the memory operation specification.

Original

```
/home/arduino/hardware/tools/avrdude \
  -DV -patmega328p \
  -Pnet:esp-link.local:23 \
  -carduino -b115200 -U -C \
  /home/arduino/hardware/tools/avrdude.conf \
  flash:w:my_sketch.hex:i 
```

Proposed change

```
/home/arduino/hardware/tools/avrdude \
  -DV -patmega328p \
  -Pnet:esp-link.local:23 \
  -carduino -b115200 \
  -Uflash:w:my_sketch.hex:i -C \
  /home/arduino/hardware/tools/avrdude.conf
```

Upgrading AVR firmware is working fine. avrdude -Pnet: works great with Uno and Pro Trinket. Dev environment is Ubuntu and IDE 1.6.9.

**Comment by tve** [comment]
You are correct, thanks for pointing it out!
