### ISSUE TITLE
MQTT: DNS lookup failed

### ISSUE THREAD

**Issue by harmeetsingh-work** [jeelabs/esp-link#169]
Hi,
First thank you for such a nice library.

ISSUE:
On boot everything works fine, even ESP gets connected to MQTT Broker successfully.

**But after Wifi Router(Home router) restart :**
ESP takes a **long long time** to connect to MQTT Broker, even if internet is there

> MQTT: Connect to mosquitto-dev.myserver:1884 0x3fffb1b0 (client=0x3fff5574)
> 856416> ip:192.168.0.14,mask:255.255.255.0,gw:192.168.0.1
> 861920> MQTT: DNS lookup failed
> 914303> ip:192.168.0.14,mask:255.255.255.0,gw:192.168.0.1
> 979020> ip:192.168.0.14,mask:255.255.255.0,gw:192.168.0.1
> 989899> MQTT: Connect to mosquitto-dev.myserver:1884 0x3fffa5d8 (client=0x3fff5574)
>   3761> MQTT: DNS lookup failed
>  35442> ip:192.168.0.14,mask:255.255.255.0,gw:192.168.0.1
>  95224> ip:192.168.0.14,mask:255.255.255.0,gw:192.168.0.1
> 130900> MQTT: Connect to mosquitto-dev.myserver:1884 0x3fffb248 (client=0x3fff5574)
> 144327> MQTT: DNS lookup failed
> 155324> ip:192.168.0.14,mask:255.255.255.0,gw:192.168.0.1
> 215344> ip:192.168.0.14,mask:255.255.255.0,gw:192.168.0.1
> 271900> MQTT: Connect to mosquitto-dev.myserver:1884 0x3fffb2e0 (client=0x3fff5574)
> 275365> ip:192.168.0.14,mask:255.255.255.0,gw:192.168.0.1
> 285368> MQTT: DNS lookup failed

**Above log keeps on looping for long long time**

Please Help !!!

**Comment by tve** [comment]
Looks like you have a DNS issue. Perhaps you configured an incorrect DNS server IP address into esp-link or your DHCP server? How do you expect mosquitto-dev.myserver to be resolved? It's not a public domain name...

**Comment by harmeetsingh-work** [comment]
Actually I have changed it, but on first run it connects successfully.

**Comment by harmeetsingh-work** [comment]
Even from Paho Client I can connect to it successfully.

**Comment by harmeetsingh-work** [comment]
If I use IP in MQTT broker then everything works fine, even after wifi router restart, and also using IP rectifies issue #170 .

**Comment by tve** [comment]
continued in #170
