### ISSUE TITLE
Unable to flash the firmware to ESP-07

### ISSUE THREAD

**Issue by crossband** [jeelabs/esp-link#176]
**Is there any guide how to flash the Esp-Link firmware to ESP-07?** 
I downloaded NodMCU Firmware Programmer, I tried flash with latest firmware, but I could not.
I would like to know about flashing addresses for each file and advanced parameters of NodeMCU programmer, e.g. Baudrate, Flash size, Flash speed and SPI Mode.
It was already installed some NodeMCU firmware before and it was working properly. Now I can not get it work. I really need it soon.

Please help. 

Edit: Now I have again followed the instructions and did as follows:
- Used NodeMCU Firmware Programmer
- 0x00000 boot_v1.5.bin
- 0x01000 user1.bin **(not 0x1000)**
- 0x3FE000 blank.bin
- Baudrate: 115200
- Flash size: 4Mbyte
- Flash speed: 80Mhz
- SPI Mode: DIO

Now I get "Fatal exeption (0)" at 74880 baud.

**Comment by tve** [comment]
It would be easier if you asked this type of question in gitter... There are also more people watching there.

If it really has 4MByte flash then the SPI mode should be QIO, just like the esp-12. The best thing to do is to erase flash and the reflash everything including the new esp_init_data_default.bin at 0x3FC000

**Comment by ShaneKirkbride** [comment]
You can check this out: https://hackaday.io/project/10457-sunleaf/log/39299-elementary-esp-to-stm32-communication or ask the question in glitter...

**Comment by Jufo84** [comment]
Hi,
Some progress in running on the ESP-07, very important to me. I will be grateful for your help.

NODEMCU report flashing is successful the ESP8266 reports Flash config restore failed on restarting. Not responding to AT or +++AT commands.

Wiring to flash ESP-07: http://dominicm.com/esp8266-flash-module-firmware/

Best Regards,
Robert

**Comment by RobertWojtowicz** [comment]
It works!, try flash:
boot_v1.5.bin to 0x00000
blank.bin to 0x3FC000
user1.bin to 0x01000

**Comment by ShaneKirkbride** [comment]
Can you say what you did to get it to work?

**Comment by RobertWojtowicz** [comment]
Use these settings for flashing (tested on 2 modules ESP-07):
boot_v1.5.bin to 0x00000
blank.bin to 0x3FC000
user1.bin to 0x01000
and this manual for wiring: http://dominicm.com/esp8266-flash-module-firmware/
Software for flashing: https://github.com/nodemcu/nodemcu-flasher/tree/master/Win32/Release

**Comment by tve** [comment]
I'm glad you got it working!

**Comment by saeidExe** [comment]
> 
> 
> It works!, try flash:
> boot_v1.5.bin to 0x00000
> blank.bin to 0x3FC000
> user1.bin to 0x01000

Hello dear friend . I have similar problem about update esp8266-07 (Blue Module) . What about esp_init_default.bin Address?

![esp8266-07 Flash map](https://user-images.githubusercontent.com/23663008/121816156-3cf4d500-cc8f-11eb-99bf-424d8983ef74.jpg)
