### ISSUE TITLE
Unable to find the correct ESP SDK to build esp-link with

### ISSUE THREAD

**Issue by prices** [jeelabs/esp-link#178]
The documentation has a link ( http://bbs.espressif.com/viewforum.php?f=5 ) but that link is broken.  It says "The forum you selected does not exist."  

Could you please point me to the correct SDK to use?

**Comment by tve** [comment]
http://www.espressif.com/en/support/download/sdks-demos?keys=&field_type_tid%5B%5D=14
SDK 1.5.4 plus patch 1.5.4.1
