### ISSUE TITLE
Multiple MQTT connection attempts

### ISSUE THREAD

**Issue by kubabuczak** [jeelabs/esp-link#180]
I'm using firmware dependent on esp-link. During startup there were multiple mqtt connection attempts, despite the first one was successful. The problem was in `wifiStateChangeCb` function in [`mqtt_client.c line 69'](https://github.com/jeelabs/esp-link/blob/master/esp-link/mqtt_client.c#L69). MQTT was connected so the broker was disconnecting old connection and establishing new for each wifiStateChangeCb callback. Adding condition for `MQTT_CONNECTED` solved it:

```
    if  (  status == wifiGotIP &&
      mqttClient.connState != TCP_CONNECTING && 
      mqttClient.connState != MQTT_CONNECTED
    ) {
```

**Comment by tve** [comment]
Makes sense. Thanks for the suggestion!

**Comment by harmeetsingh-work** [comment]
@jakkubu  Thank you very much. 👍 :)

**Comment by tve** [comment]
This is fixed on master. Thanks!
