### ISSUE TITLE
Able to flash based on MQTT subscription?

### ISSUE THREAD

**Issue by SpiraMirabilis** [jeelabs/esp-link#181]
Is it possible to initiate a flash to a connected device based on bytes received from a MQTT subscription? I am trying to coordinate how to keep a bunch of multiple devices in sync.

**Comment by tve** [comment]
Nope, that is currently not supported.

**Comment by tve** [comment]
I'm going to close this issue. It could be a feature request but due to the buffering issues this raises I'm not sure it's realistic in the current state of things. But if someone want to work up a PR, I'm open to it.
