### ISSUE TITLE
Share LED for both wifi and serial?

### ISSUE THREAD

**Issue by beikeland** [jeelabs/esp-link#185]
I mostly have WeMos D1 mini modules, that only have 1 LED, and I would prefer if this was able to indicate both wifi connection and serial traffic.

I.e. solid on when connected, and flashing on traffic. Is this feasible to implement in a future version?

**Comment by tve** [comment]
the wifi led already uses several flashing modes to indicate whether it's in AP vs STA mode and whether it's looking for the AP, waiting for a DHCP lease, or connected. So I'm afraid there is a bit of overload... I'm OK with a pull request that adds an option as you describe...

**Comment by tve** [comment]
closing 'cause nothing has moved here in a very long time.
