### ISSUE TITLE
Review for pull request: V2 adding uart format support

### ISSUE THREAD

**Issue by bitdump** [jeelabs/esp-link#190]
Hi,

I have a version 2 of the uart format support
ready for review:
#189

The V2 Address some feed back mentioned in the V1 change.
Like white space and uart init base on flashConfig.

Thanks

**Comment by tve** [comment]
Thanks, merged. Next time you don't need to make a fresh pull request. You just keep committing changes to your branch and they appear in the pull request automatically.
Thanks for all your work!
