### ISSUE TITLE
esp heats up at work

### ISSUE THREAD

**Issue by RobertWojtowicz** [jeelabs/esp-link#192]
Is it normal that the module esp-07 (esp-link) so much hot (+45 C). He works well with Roomba, but I ask whether it is normal :)

Best Regards,
Robert

**Comment by tve** [comment]
this is not normal. at least I haven't found that they get this hot. are you sure it's the esp and not a voltage regulator you may have on the PCB that gets hot?
If it's the esp8266 then I assume that it's driving some output pin that has too small a pull-up resistor or that is connected to something that is also outputting causing the two drivers to "fight".
Some ways to cause this type of issue it to hard-wire gpio0, gpio2, or gpio15 instead of using pull up/down resistors.

**Comment by RobertWojtowicz** [comment]
Perhaps this voltage regulators on the board ESP-07, the whole is under the metal sheld (he is hot). The external voltage regulator step down is set to 3V. Here are the photos of my module:
http://icebox.pl/roomba/roomba_01.jpg
http://icebox.pl/roomba/roomba_04.jpg
http://icebox.pl/roomba/roomba_02.jpg
http://icebox.pl/roomba/roomba_03.jpg

I did not use resistor pull-up / down (10k?) for gpio15 and gpio 0, gpio 2 is not connected.

The module is working properly, communication with the Roomba work, the fact that the Roomba always sending data.

**Comment by tve** [comment]
Nice PCB! There is no voltage regulator under the metal shield, just he esp8266 and the flash chip plus some passives. You are feeding it with 3.3v not 5v, right? If you can, measure the power current, it should consume around 70-80mA.

**Comment by tve** [comment]
> I did not use resistor pull-up / down (10k?) for gpio15 and gpio 0, gpio 2 is not connected.
> Most likely that's your problem. gpio2 needs to be pulled high to ensure proper booting. Others have reported issues when gpio15 is hard-wired to gnd. The chip outputs its clock at reset on gpio0, so hard-wiring that is not a good idea either. If esp-link is configured to output one of the LED signals on gpio0 or 15 you're also going to run into trouble...

**Comment by RobertWojtowicz** [comment]
> Nice PCB! There is no voltage regulator under the metal shield, just he esp8266 and the flash chip plus some passives. You are feeding it with 3.3v not 5v, right? If you can, measure the power current, it should consume around 70-80mA.

THX :) Yes are feeding it with 3V (for safety), current 85mA, peak to 110mA.

> Most likely that's your problem. gpio2 needs to be pulled high to ensure proper booting. Others have reported issues when gpio15 is hard-wired to gnd.

Ok, gpio15 is hard-wired to gnd and gpio 2 is not connected, I should let go both (gpio 2 and gpio 15) to the ground by a resistors on what value? 
It's a bit strange, because everything works :) only heats up: /

> esp-link is configured to output one of the LED signals on gpio0 or 15 you're also going to run into trouble...

I do not use GPIO to LEDs, only (as an option in the future for wakeup) I have connected at GPIO12 by a resistor and zener diode.

**Comment by tve** [comment]
The proper way to connect the esp8266 is to use a pull-up resistor in the 4.7k-10k range for gpio0 and gpio2, and a pull-down for gpio15. You need to drive gpio0 low at boot to get into flash-programming mode but not otherwise.
85mA avg sounds about right. You should really use 3.3v or the wifi might not work as well, e.g. less power. If the metal case gets warm then I would say it's OK, if it gets too hot for your finger then you have a problem as far as my experience goes.

**Comment by RobertWojtowicz** [comment]
> You should really use 3.3v or the wifi might not work as well, e.g. less power. 

According to the manufacturer ESP-07 (datasheet) should work properly from 3V to 3.6V.
I set 3V because the 3.3V to gpio 12 (from the wakeup) happened cumulatively in peak 3.6V. When set to 3V, for gpio 12 is the peak 3,25V. It is based on the proven theory schema, which I modified my version.

> You need to drive gpio0 low at boot to get into flash-programming mode but not otherwise.

Yes, of course I have two pins (GPIO 0 and GND) and jumper for flashing

> If the metal case gets warm then I would say it's OK, if it gets too hot for your finger then you have a problem as far as my experience goes.

I measured the meter was maximally ~ +45 C, it was never too hot for my finger :)

**Comment by RobertWojtowicz** [comment]
I researched myself ESP-07 without a voltage regulator, directly handed 3.3V. Without connecting TX and RX heats up to + 39C, something must be wrong, tomorrow will use a pull-down 10k for GPIO15.
GPIO2 is disconnected - there is a need to do pull-up? GPIO0 are disconnected. 
I looked at different schemes to connect, whether for CH_PD need to use pull-up? (I have connected directly to Vcc).

**Comment by tve** [comment]
you should definitely pull-up gpio0 and gpio2. If you don't it may work, but can be sensitive to noise. You can hard-wire ch_pd unless you want to drive it from gpio16 for wake-up from deep sleep.

**Comment by RobertWojtowicz** [comment]
> you should definitely pull-up gpio0 and gpio2

But gpio0 is connected only when flashing, I understand that in the normal mode, the boot is needed Connection pull up. Why pull-up for GPIO2?
Schematic for the ESP-12: http://souliss.net/images/2015-07/ESP_min.png

**Comment by tve** [comment]
To get to the source, download the esp8266 pin list http://www.espressif.com/en/support/download/documents?keys=&field_type_tid%5B%5D=14 and look at the strapping tab. gpio0, gpio2, gpio15 form a 3-bit field that determines where the chip boots from.

**Comment by RobertWojtowicz** [comment]
Thank you, summing:

Normal boot: 
GPIO15 (MTDO), pull-down (L)
GPIO0, pull-up (H)
GPIO02, pull-up (H)
CH_PD, pull-up (H) - Optional!

Flash boot:
GPIO15 (MTDO), pull down (L)
GPIO0, pull-down (L) - connect to GND
GPIO02, pull-up (H)
CH-PD, pull-up (H) - Optional!

**Comment by BGatRMIT** [comment]
G'day Jufo84,
Just a rule of thumb following on from TVE above. Any pin set to be an
input on a micro should be pulled high or low. (Depending on what you want
it's default state to be).
Otherwise the input will "float" and randomly be either state. Just the
capacitance from your hand waving near it can change the state.
So by tying it to one state or the other via a resistor ensures predictable
behaviour.

Ben

**Comment by JohnOH** [comment]
To keep battery consumption at a minimum and assuming no other constraints, choice of high or low depends on the typical state of the pin in actual operation.

John.

**Comment by RobertWojtowicz** [comment]
I made a modify the PCB, I added a pull-up / down resistor 10k, and continues to heat up :( Maybe this is the bug esp-link in ESP-07 ?:
http://icebox.pl/roomba/mod.jpg

**Comment by RobertWojtowicz** [comment]
My ESP-07 died after 2 hours after modifications pull-up / pull-down :( I decided to buy tested ESP-12. It good wirinig ?, but gpio2 everywhere is not used:
http://img15.hostingpics.net/pics/790940ESP12SCHEMA.jpg
https://ae01.alicdn.com/kf/HTB1a.JWKpXXXXc_XVXXq6xXFXXX4/201898713/HTB1a.JWKpXXXXc_XVXXq6xXFXXX4.jpg

**Comment by BGatRMIT** [comment]
G'day Jufo84,
That's unfortunate. Sounds like the 07 was faulty.
Not quite sure what you are asking though re the 012?

Ben

**Comment by RobertWojtowicz** [comment]
I would like to confirm that the wiring diagram ESP-012, who presented is correct. ESP-12 is more popular and officially supported by the esp-link.

**Comment by BGatRMIT** [comment]
Well I have run one without a problem for over a month now. Occasional
serial glitches but I suspect that's the arduino not the esp.
The main fault I have researched with the ESP is the stability of the psu.
Ie if you don't provide enough mA and caps to keep the Voltage stable they
reset themselves.

Ben
