### ISSUE TITLE
Arduino Due Support

### ISSUE THREAD

**Issue by sebgiles** [jeelabs/esp-link#198]
Is it currently possible to flash a sam3x chip (arduino due)? Readme hints that programming various arm processors is possible, however the command bossac, used to flash the chip, does not allow users to specify a network address in place of a serial port

**Comment by tve** [comment]
I'm not familiar with the sam3x series. Most arm chips need a combination of boot0 and reset to get into serial programming mode. In general, esp-link can issue the sequence and I'm happy to add a new one given the necessary information. WRT specifying a network address, a work-around it to either use a different tool or to use serial port forwarding.

**Comment by rocketjosh** [comment]
Hey there - I'd be interested in this as well. Let me know if I can help with testing! Thank you for the excellent work.

**Comment by steamboating** [comment]
Because my wood-walker.com robot on which i am using ESP-Link and ESP-client is based on the Arduino DUE I would be happy to test such features also - but sorry I am not a big help in programming something like this...

**Comment by rocketjosh** [comment]
Here is a little more information about how the bootloader works on Arduino Due:

http://playground.arduino.cc/Bootloader/DueBootloaderExplained

**Comment by tve** [comment]
closing 'cause nothing has moved here in a very long time.
