### ISSUE TITLE
Current(oct 12 2016) source build causes loop on esp-12 

### ISSUE THREAD

**Issue by fuzzball03** [jeelabs/esp-link#203]
After building the latest source with docker, esp-12 goes into boot loop when attempting to start esphttpd. 
Throwing "fatal exception 1" or another "fatal exception 28" 

Same behavior with two units.
Attempted fixes/workarounds:
1) erased all flash memory of ESP
2) flashed with & without init bins
3) various SPI modes... QIO, DIO, 80mhz, 40mhz.
4) v2.2.3 build flash & boots without issues
5) rebuilt with slightly newer SDK(throws fatal exception after loading User1)

Build environment:
1) docker windows
2) latest GIT pull of esp-link (Oct 12 2016)
3) provided esp SDK and "ESP8266 NONOS SDK V2.0.0 20160810"
4) no makefile changes made except host-target

I'm hoping something is wrong with my build since no other issues of this appear to be reported.

Any thoughts or help?
Or is this an issue of the current master source?

**Comment by fuzzball03** [comment]
Well... I was about to paste a copy of the console when this happens.
I hooked up one module... No boot loop or exception. Hmm. Odd? Hooked up the other. Same thing...

Well look at that... booted up just fine now. So, i'm at a loss - I tried all night last night only for it to suddenly work now.

WiFi scanning did fail on both modules till I manually entered SSID & key... As soon as I pushed connect, the scan displayed the SSID results.
Connected fine now though - all good?

![capture](https://cloud.githubusercontent.com/assets/5809716/19616180/4fa2c2e4-97d2-11e6-9c83-0812611da585.PNG)

**Comment by fuzzball03** [comment]
Well... Did a reset, it looped 8 or so time then booted. Here's the console log:

```
ets Jan  8 2013,rst cause:2, boot mode:(3,6)

load 0x40100000, len 2408, room 16
tail 8
chksum 0xe5
load 0x3ffe8000, len 776, room 0
tail 8
chksum 0x84
load 0x3ffe8310, len 632, room 0
tail 8
chksum 0xd8
csum 0xd8

2nd boot version : 1.6
  SPI Speed      : 80MHz
  SPI Mode       : QIO
  SPI Flash Size & Map: 32Mbit(512KB+512KB)
jump to run user1 @ 1000

▒▒▒x▒n▒▒>r▒▒▒n▒b
▒▒▒l`▒r▒8▒l #
▒
r▒▒▒▒▒8▒▒▒
▒
r▒▒▒▒▒8▒
▒▒▒
▒lrr▒▒l▒Ğ▒▒
▒▒b▒▒b▒ ▒l▒▒l▒b▒b▒▒8~▒n▒n▒▒▒▒l▒▒▒n▒$▒
▒
&!!!▒
   134>
   134> ** esp-link master - 2016-10-21 04:09:26 - development
   134> Flash config restore ok
   135> CONN led=2
   335> Wifi init, mode=STA
   336> Wifi uses DHCP, hostname=esp-link
   336> "ip": "0.0.0.0"
   336> "netmask": "0.0.0.0"
   338> "gateway": "0.0.0.0"
   340> "hostname": "esp-link"
   343> sleep enable,type: 2
   346> Httpd init, conn=0x3fff37a0
   349> No user file system found!
   352> Serbridge pins: reset=12 isp=13 swap=0
   365> Reset cause: 2=exception
   365> exccause=0 epc1=0x4021f23f epc2=0x0 epc3=0x0 excvaddr=0x0 depc=0x0
   366> Flash map 4MB:512/512, manuf 0xEF chip 0x4016
   371> ** esp-link master - 2016-10-21 04:09:26 - development: ready, heap=21592
   378> SNTP timesource set to us.pool.ntp.org with offset 0
   383> initializing user application
   386> Waiting for work to do...
   390> mode : sta(5c:cf:7f:19:a1:ec) + softAP(5e:cf:7f:19:a1:ec)
   395> add if0
   397> add if1
   398> dhcp server start:(ip:192.168.4.1,mask:255.255.255.0,gw:192.168.4.1)
   406> bcn 100
   528> scandone
   529> state: 0 -> 2 (b0)
   531> state: 2 -> 3 (0)
   534> state: 3 -> 5 (10)
   534> add 0
   534> aid 7
   534> cnt
   558>
   558> connected with BerryN, channel 8
   558> dhcp client start...
   559> Wifi connected to ssid BerryN, ch 8
  1115> ip:192.168.1.202,mask:255.255.255.0,gw:192.168.1.1
  1115> Wifi got ip:192.168.1.202,mask:255.255.255.0,gw:192.168.1.1
  1117> host_name = esp-link
  1120> server_name = _http._tcp.local
 15346> Wifi check: mode=AP+STA status=5
 15346> Wifi got IP. Going into STA mode..
 15346> bcn 0
 15346> del if1
 15347> pm open,type:2 0
 15350> mode : sta(5c:cf:7f:19:a1:ec)
 15553> Turning OFF uart log
```

**Comment by tve** [comment]
Not sure what happened, but it seems you sorted it out. Please reopen if you find an issue again.

**Comment by mountaindude** [comment]
I am seeing a similar boot loop issue. 

Using v3.2.47 on a Wemos D1 mini R2.2.
All is well until I set the uC console speed to 1200 baud. After a reboot or power cycling the boot loop appears: 

   989> "ip": "0.0.0.0"
  1197> "netmask": "0.0.0.0"
  1447> "gateway": "0.0.0.0"
  1697> "hostname": "esp-link-1"
  1981> sleep enable,type: 2
  2231> Httpd init, conn=0x3fff4128
  2539> No user file system found!
  2839> SerbridgÿîXcHHH¨H¢òj
   141> ** esp-link v3.2.47-g9c6530d
   141> Flash config restore ok
   141> CONN led=14
   194> SER led=2
   353> Wifi init, mode=AP+STA
   619> Wifi uses DHCP, hostname=esp-link-1
   994> "ip": "0.0.0.0"
  1203> "netmask": "0.0.0.0"
  1453> "gateway": "0.0.0.0"
  1703> "hostname": "esp-link-1"
  1986> sleep enable,type: 2
  2236> Httpd init, conn=0x3fff4128
  2544> No user file system found!
  2844> SerbridgÿÌÃ0!HHH¨H¢òj
   143> ** esp-link v3.2.47-g9c6530d
   143> Flash config restore ok
   143> CONN led=14
   196> SER led=2
   355> Wifi init, mode=AP+STA
   621> Wifi uses DHCP, hostname=esp-link-1
   996> "ip": "0.0.0.0"
  1204> "netmask": "0.0.0.0"
  1454> "gateway": "0.0.0.0"
  1704> "hostname": "esp-link-1"
  1988> sleep enable,type: 2
  2238> Httpd init, conn=0x3fààüààüààààààààààààüààüààààüüüüàj
  1201> "netmask": "0.0.0.0"
  1451> "gateway": "0.0.0.0"
  1701> "hostname": "esp-link-1"
  1985> sleep enable,type: 2
  2235> Httpd init, conn=0x3fff4128
  2543> No user file system found!
  2843> SerbridgüÙ


Changing the speed to for example 9600 baud works, as does keeping the speed at 115200.
The thing for me is that I am trying to connect a 1200 baud only device to wifi... so I need that (super slow) 1200 baud mode.

**Comment by farthinder** [comment]
@tve I seem to be having the same problem as @mountaindude, in my case I need to set baud to 2400 and all works well until I reset the wemos D1 Mini, after that I ends upp in a boot loop and gives error: No user file system found!

I'm running v.3.0.14

@tve would you consider reopening this issue?

**Comment by farthinder** [comment]
For anyone who runs in to the same problem, the solution that works for me to get out of the boot loop is to use the Arduino IDE to flash any sketch and make sure to under the tools menu set: 
Erase Flash: All...
