### ISSUE TITLE
Empty wifi configuration after a while.

### ISSUE THREAD

**Issue by hetii** [jeelabs/esp-link#210]
I notice some odd issue regarding wifi configuration.
It looks like after a while or after some unknow condition esp-link lost his wifi settings.
In terminal esp is set to AP mode and with all IPs set to 0.0.0.0
Even when I reflash it using user1.bin and blank.bin the settings is still empty and don`t switch back to AP with DHCP to be able to connect to it on 192.168.4.1

Only by calling `esptool.py erase_flash` and reflashing, configuration is set to default one.

**Comment by minida28** [comment]
I think I remember I had this situation before (or similar; can't remember exactly).
Do you mind try this:
1. Flash the esp using older esplink version - I used version 2.1.7
2. Then update to the latest firmware using wiflash
Steps above solved my problems (unable to set IP address manually or via DHCP).

**Comment by tve** [comment]
Mhh, I'm not sure how to reproduce this, any ideas?

**Comment by tve** [comment]
closing 'cause nothing has moved here in a very long time.
