### ISSUE TITLE
Where are upgrade firmware and web server pages?

### ISSUE THREAD

**Issue by kiralikbeyin** [jeelabs/esp-link#212]
I just flashed 2.2.3 and there is no esp_init_data_default.bin file also there is no "upgrade firmware" + "Web server" on left menu
How can i enable upgrade firmware and web server pages?

Is there any esp stand alone version? Do i have to install an arduino etc?

**Comment by WheresWally** [comment]
I think they are only in V3. Also when going from V2.2.3 to V3 you might need to Ctrl-F5 to refresh your browser.

**Comment by tve** [comment]
Sorry, as WhereWally mentioned, those features are only in v3.
