### ISSUE TITLE
Where I can find the .bin files for flashing the esp-link firmware to an esp-8266 ESP-01 ?

### ISSUE THREAD

**Issue by roesl** [jeelabs/esp-link#217]
Hello,

are there any ready flash files for the project ?

regards
Georg

**Comment by CharlyBrok** [comment]
Hello,
You can find in https://github.com/jeelabs/esp-link/releases
(Found in "Release & Downloads" in readme.

**Comment by roesl** [comment]
thank you for the fast Reply - it works fine !!

**Comment by minida28** [comment]
Don't forget to close the issue if has been resolved.
