### ISSUE TITLE
Upload the HEX file to the ESP_LINK and then flash the attached uController please?

### ISSUE THREAD

**Issue by WheresWally** [jeelabs/esp-link#219]
As a possible new feature, seeing as we now can flash the ESP firmware, wouldn't it be possible to use the same mechanisms to upload a HEX file as is done by the flash firmware and by the webserver, and then use the same routines for flashing the attached ucontroller?
I hope this can be a feature as it is more intuitive than using avrdude or curl.
Terry

**Comment by tve** [comment]
Yes, this would definitely be possible. I'm not sure it's that convenient. Every time you make a change and need to re-upload you end up having to click around a bunch to perform the upload in your browser. But I'm certainly open to a PR :-)

**Comment by tve** [comment]
closing 'cause nothing has moved here in a long time.
