### ISSUE TITLE
RESET Pin high impedance when quiescent please

### ISSUE THREAD

**Issue by WheresWally** [jeelabs/esp-link#220]
Possible bug fix or improvement.
I have a MEGA with a watchdog chip as well as the ESP_LINK. The watchdog chip cant reset the MEGA , but the ESP_LINK can. The watch chip wire is in a high impedance state when not needed.
If I remove the Reset wire from the ESP_LINK (on a ESP8266-01) then the watchdog does work.
I installed a diode between the ESP-LINK Reset and the MEGA, then the wacthdog chip and the ESP_LINK can both reset the MEGA as desired.
Like this .
MEGA.Reset  ---|>| ---- ESP_LINK.Reset.

Does the ESP_LINK.Reset pin go to a high impedance (an input) state when not needed to perform a reset?
If not, can it be made to do that please?
Terry

**Comment by tve** [comment]
This could definitely be implemented. A PR would be awesome ;-)

**Comment by WheresWally** [comment]
I am not sure what a Pull request requires of me.
I have so far found that in the file 'serbridge.c,' the lines with  **GPIO_OUTPUT_SET(mcu_reset_pin, 1);** will most likely need to be changed to set the pin as an input. Not sure how to do that yet. 
I guess it will be a function to undo what this one has set **makeGpio(mcu_reset_pin);** 

That function is defined in 'serled.c' but it only uses function 3 to set the pin as an output.
What function sets it as an input?

Ah it seems that **GPIO_DIS_OUTPUT()** will set a pin as an input. Thanks to a read of the reference manual.

So I am thinking that all that needs changing in **serbridge.c** is
```
GPIO_OUTPUT_SET(mcu_reset_pin, 1);
```
to
```
{GPIO_OUTPUT_SET(mcu_reset_pin, 1);GPIO_DIS_OUTPUT(mcu_reset_pin);}
```

**Comment by tve** [comment]
Yes, that should work, but you also need to re-enable the pin when it's set to 0. No need for curly braces.

A PR is more involved 'cause this would need a setting in the UI and be persisted in flash. You can of course just make the changes locally for yourself ;-).

**Comment by tve** [comment]
closing 'cause nothing has moved here in a long time.
