### ISSUE TITLE
Bridge wifi to serial

### ISSUE THREAD

**Issue by silvius76** [jeelabs/esp-link#229]
Hi,

I would like to use esp8266mod ai-thinker with esp-link in bridge mode ( full trasparent serial ) for that:

![serial](https://cloud.githubusercontent.com/assets/7814074/21154200/cc2a4138-c16d-11e6-953d-8c79ef188fc2.JPG)

I tested it in different configuration, but it didnt work
where I should connet (esp8266) serial pin like CTS, RTS, DTR, DSR ?

Regards

**Comment by tve** [comment]
esp-link does not currently support flow-control, sorry.

**Comment by silvius76** [comment]
Thanks

I have 2 possibility, software or hardware handshakle


SOFTWARE:
![software handshake](https://cloud.githubusercontent.com/assets/7814074/21274842/77d075d0-c3ca-11e6-8aa0-4a75d5b5bcb5.jpg)

HARDWARE:
![hardware handshake](https://cloud.githubusercontent.com/assets/7814074/21274858/8b6f1024-c3ca-11e6-979c-008c7f08b4c9.jpg)

is possible with software flowcontrol ?

Regards

**Comment by tve** [comment]
if end-to-end flow control through esp-link works for you, then it may be OK, but esp-link itself does not implement flow-control.

**Comment by tve** [comment]
closing 'cause nothing has moved here in a long time.
