### ISSUE TITLE
The problem with mega2560

### ISSUE THREAD

**Issue by annak1n** [jeelabs/esp-link#237]
I'm trying to upload a sketch in Mega 2560 on bridge ESP-Link but Arduino IDE gives an error:
`avrdude: stk500v2_ReceiveMessage(): timeout
avrdude: stk500v2_ReceiveMessage(): timeout
avrdude: stk500v2_ReceiveMessage(): timeout
avrdude: stk500v2_ReceiveMessage(): timeout
avrdude: stk500v2_ReceiveMessage(): timeout
avrdude: stk500v2_ReceiveMessage(): timeout
avrdude: stk500v2_getsync(): timeout communicating with programmer
`

But in the console logs come from Mega 2560.
How i can fix it ?

**Comment by FernandoGarcia** [comment]
https://github.com/jeelabs/esp-link/issues/87

**Comment by tve** [comment]
Implemented in v3.2
