### ISSUE TITLE
TLS 1.2 Support

### ISSUE THREAD

**Issue by limweichiang** [jeelabs/esp-link#242]
First of all, let me thank you for your great work. I've had a head-scratching few weeks trying to figure out how to get Arduino.org's Uno Wifi to work with ThingSpeaks. It seems their sample "ciao" code doesn't work, and their libraries, whatever has been changed from the original sources (esp-link and SC16IS750), is quite badly documented/coded. I managed to flash up to esp-link, and got the ThinkSpeak elclient working right off the bat.

I saw that Espressif has released an MBEDTLS patch for SDK 2.0, and wonder if this can be built into esp-link 3.0, since it is already being developed against SDK 2.0? It would be great to gain TLS 1.2 support for Arduino, i believe it's a requirement for Amazon AWS's IOT Hub. I'm just getting started on Arduino and can't contribute code, but I'll be happy to help test it out.

Thank you.

**Comment by tve** [comment]
This is possible in principle but it requires first freeing up enough memory to fit TLS. I'm closing this ticket as dup of #19
