### ISSUE TITLE
wiflash exits with "HTTP server doesn't seem to support byte ranges. Cannot resume."

### ISSUE THREAD

**Issue by PuceBaboon** [jeelabs/esp-link#256]
I'm inclined to believe that this issue was caused by the very old (v2.0-beta2-46) version of esp-link already loaded on the ESP, along perhaps, with a fairly ancient OS (an Ubuntu 12-04 LTS derivative ...but with curl  version 7.22).  However, I'm just flagging it here in case someone else hits the same problem.

Using the wiflash utility included in the esp-link-v3.0.14-g963ffbb package from this site, the upgrade of the older v2-beta version failed when trying to retrieve the "/flash/next" file with the error from curl:-

```
HTTP server doesn't seem to support byte ranges. Cannot resume.
```
I was able to continue by changing line No. 82 in wiflash from:-

```
next=`curl -m 10 $v -s "http://$hostname/flash/next"`
```

to:-

```
next=`curl --no-continue-at -m 10 $v -s "http://$hostname/flash/next"`
```

Note that I didn't change any of the other calls to curl in the file.

Great package, BTW.  A very useful utility, well implemented and getting better all of the time.  Many, many thanks for the ton of hard work you've obviously put into it.  Here's my cack-handed use case:-

https://esp8266hints.wordpress.com/2016/03/26/implementing-a-wireless-console-using-jeelabs-esp-link/

**Comment by tve** [comment]
Interesting use-case! I've never encountered this issue. I don't understand why curl would use byte ranges on a tiny GET request...
