### ISSUE TITLE
Uno Wifi

### ISSUE THREAD

**Issue by scallas** [jeelabs/esp-link#270]
Hi there
Is there a specific way/method to flash the Arduino Uno Wifi's ESP8266?
Im using Windows Vista.

Cheers
Schalk

**Comment by astronomer80** [comment]
Hi, see this guide:
http://www.arduino.org/learning/tutorials/advanced-guides/how-to-change-the-firmware-on-an-arduino-uno-wifi
or this one
http://www.arduino.org/learning/tutorials/advanced-guides/arduino-uno-wifi-firmware-updater

With the Arduino Uno WiFi Develeper edition I think that the best way is to use the OTA. Note that using the USB2Serial version without the patch on the bootom of the board, the maximum baudrate is 9600.

**Comment by scallas** [comment]
Thanks. Will try it. 

Schalk

**Comment by scallas** [comment]
I tried it but am unable to select the esp-link firmware with the Uno Wifi updater tool.  Do I have to copy the firmware in a certain folder?

**Comment by JAndrassy** [comment]
Instructions in FLASHING.md are ok for the Uno Wifi dev. ed. Don't forget to prepare the board with EspRecovery sketch and bootloader mode.
(btw. Uno Wifi updater tool has the firmware list hardcoded.)
