### ISSUE TITLE
Is this project about using esp8266 as external wifi adapter?

### ISSUE THREAD

**Issue by themakerman** [jeelabs/esp-link#274]
So if i connect esp running this project does that means it will behave as an external wlan adapter over usb? In other words if i do iwconfig on my linux machine will it show esp8266 as wlan1 being external wireless adapter? Sorry but i went through the description of project but i was unable to understand it. Thanks once again.

**Comment by uzi18** [comment]
No, it is more like serial converter/bridge but with wifi connection

2017-03-11 18:55 GMT+01:00 Gaurav Harchwani <notifications@github.com>:

**Comment by tve** [comment]
esp-link is not suited to be used as linux Wifi adapter.
