### ISSUE TITLE
Flashing ATMega328 from SPIFFS

### ISSUE THREAD

**Issue by c-mysec** [jeelabs/esp-link#284]
I have an Arduino Pro Mini with an Wemos D1 Mini (ESP8266) behind a NAT.
The only way I can think of to upload a new sketch to the ATMega is by "downloading" the firmware first to the D1 Mini SPIFFS and then flashing the ATMega.
I know nothing about the built-in programmer.
Is there an easy/ready way to do this?
Or is there anything similar to this. any suggestion? (i.e. source code to look at, directions,)

**Comment by tve** [comment]
I'm afraid I don't know much about the configuration you mention. Esp-link allows you to upload a sketch through the esp8266 to an atmega.
