### ISSUE TITLE
Get COM PORT on pc

### ISSUE THREAD

**Issue by notsolowki** [jeelabs/esp-link#286]
maybe I'm missing something but is there a way to use 2 ESP 8266's to basically get the full experience. for instance if I had a second esp8266 with esp link that connects to the first host esp8266 receives that data and puts it through a rs232 to usb adapter? thankyou

**Comment by uzi18** [comment]
You still need another host to exchange data between esp-links.


11.05.2017 11:02 AM "notsolowki" <notifications@github.com> napisał(a):

**Comment by tve** [comment]
esp-link doesn't create a "stand-alone" serial bridge between two esp8266's. It's always between some computer and the serial port on the esp8266.
