### ISSUE TITLE
Arduino UNO

### ISSUE THREAD

**Issue by delchrys** [jeelabs/esp-link#291]
I have succefully flashed ESP8266 before, but is this firmware compatible with arduino UNO WiFi??
Or am i stuck with their old firmware???

**Comment by tve** [comment]
sorry, I don't have an uno and can't dev/test this. Maybe someone else has info.

**Comment by jandrassy** [comment]
it is, just Uno Wifi uses 40MHz crystal for the ESP8266. I used original esp-link release binaries, just changed with hex editor one byte right after the sequence 00 00 01 01 02 03 04 05 from 01 to 00. (see core_esp8266_phy.c)

**Comment by delchrys** [comment]
I have already figured it out
