### ISSUE TITLE
Where is esp_init_data_default.bin as per instructions

### ISSUE THREAD

**Issue by gibbedy** [jeelabs/esp-link#292]
I'm getting an error trying to flash esp-link for the first time.
Where am I to get the file esp_init_data_default.bin as it's not in my tgz
Thanks.

**Comment by tve** [comment]
please download https://github.com/jeelabs/esp-link/releases/tag/V3.0.14 and not an older version, unless you have a problem with the new version

**Comment by gibbedy** [comment]
Thanks. I didn't come across that.
