### ISSUE TITLE
Softserial support

### ISSUE THREAD

**Issue by infernix** [jeelabs/esp-link#316]
Would you consider supporting it? It will allow for using any GPIOs; in my use case I cannot use standard  TX/RX because at ESP bootup it prints garbage which breaks the device I'm talking to, and I can't use swapped because due to the level converter, GPIO15 is always high and at ESP bootup it goes into sdio/sdcard mode.

With softserial you can set any GPIO which will avoid the above scenario. Even if it's optional it'd be very useful I think?

**Comment by tve** [comment]
Softserial has come up in the past and some folks have tried it. I'm not willing to support it 'cause it's way too flakey, but that doesn't mean you can't add it to your version of esp-link :-). The fundamental issue is that the wifi device layer needs to have the cpu for extended periods of time (relative to a serial bit time) and so serial becomes very unreliable.
Why do you need a level shifter on GPIO15? It becomes TX so you could have a driver that does not pull gpio15 high.

**Comment by infernix** [comment]
Device I'm talking to is 5V serial, so to my understanding that needs a level shifter, and when the device is on it's pulled high. But yeah, if you have no plans then I'll just write a simple sketch with softserial and be done with it :+1:
