### ISSUE TITLE
Question ESP32 Port

### ISSUE THREAD

**Issue by dpulvermacher** [jeelabs/esp-link#318]
We need the Bluetooth connectivity in the ESP32.
Can the the esp-link project be ported to the ESP32?
How much work would it be?

Thanks!
Kerry

**Comment by tve** [comment]
I have no experience with the ESP32, so I cannot comment on this, sorry.

**Comment by Sergio-tix** [comment]
ESP32 more productive and has 3xUART hardware up to 5Mbps (from datasheet). It makes sense to port. In combination with Tibbo software, you can get a converter for several protocols at once, RS485/232/CAN applying cheap converters from Ali, as MAX3232.
p.s. If the code was written in an environment similar to arduino, nothing would have to be ported, it worked out of the box.

**Comment by uzi18** [comment]
yes, we know but someone need free time to port it

**Comment by eried** [comment]
ESP32 is almost the same price as the ESP8266, has anyone started/tried to port esp-link?

**Comment by tve** [comment]
Yeah... 'been using micropython on the esp32 for a year now, really liking it... it would make sense to port the UI to micropython on the esp32 and create a version of esp-link that is easily scriptable... but that does need time and motivation...
