### ISSUE TITLE
Problem getting this to work, Sync failed!

### ISSUE THREAD

**Issue by MartinTerp** [jeelabs/esp-link#327]
Hi guys.

Im still pretty new to arduino and im trying to connect my esp8266 running esp-link v2.2.3.
I have connected it using this schematic: https://i.stack.imgur.com/KYbW1.png

I have no problem connecting to the esp_link interface.

Im trying to use the REST example on the EL-Client lib.

- Arduino UNO
- ESPLINK baud: 115200
- SLIP Enabled

The message on the Serial Monitor:
`EL-Client starting!
ÀÀClient sync failed`

What am i missing?
Thanks in advance.

**Comment by uzi18** [comment]
try test-reset example, first
try also esp with latest firmware 3.x

2017-08-19 20:53 GMT+02:00 MartinTerp <notifications@github.com>:

**Comment by MartinTerp** [comment]
@uzi18 Thanks for your response.

I have updated to 3.0.14, and tried running the test-reset example as you said, and im, getting the same error "ÀÀEl-Client sync failed"

Also, in the uc console, i get this when booting up:
`["#��a�q��������M�]�m�|��*�0�������������ߑϑ�����ߐϐ���������o���q�`����ϓߓ��� �0�g�p������������ U`

**Comment by uzi18** [comment]
OK now try sketch like this:

void setup() {
Serial.begin(115200);
Serial.println("test");
Serial.println("test");
Serial.println("test");
Serial.println("test");
Serial.println("test");
}

upload it to uno

open uc console - choose 115200, 8n1
now please push reset on uno

did You received test lines in uc console?

if not You have wrong UNO selected or Your uno have got wrong crystal
selected.



2017-08-19 21:55 GMT+02:00 MartinTerp <notifications@github.com>:

**Comment by MartinTerp** [comment]
Apprently i have switched the to rx/tx wires, worked after switching them around

**Comment by uzi18** [comment]
So You didn't connected it like on image you attached.

19.08.2017 11:46 PM "MartinTerp" <notifications@github.com> napisał(a):
