### ISSUE TITLE
Serial - Telnet passthrough

### ISSUE THREAD

**Issue by DouglasPearless** [jeelabs/esp-link#344]
I have spent several weeks trying to diagnose and fix and issue and I have traced it back to ESP-Link.

Scenario: LaserWeb 4 <> AP <>Telnet ESP8266 running latest ESP-Link UART <> Smoothieboard.

The LaserWeb sends a command to Smoothie, Smoothie returns an"ok" or another response like "<Run ..." or "<Idle ..." back; this progresses nicely, then the message back to LaserWeb start getting corrupted and even have parts different responses get mixed up

Examplem from the ESP Console:
Was expecting:
```
X249.00 S0.6771
ok
```
Got
`X249.0 S0.6o771k`

HELP!

Note: I have varied the baud rate from 19200 to 250000, same issue.

:-)

**Comment by DouglasPearless** [comment]
So, I assume no-one else has this issue?
Not solvable?

**Comment by uzi18** [comment]
Any screenshot?
Did You tried to send cmd directly from ESP Console?

**Comment by DouglasPearless** [comment]
I am closing this issue as I have traced the root cause to the Smoothie part of the chain of events and not the ESP.
