### ISSUE TITLE
Baud lower than 57600

### ISSUE THREAD

**Issue by roboticboyer** [jeelabs/esp-link#35]
TVE
Your ESP-link is also useful to add an easy wifi connection for Arduino Uno using SWserial. 
The problem is the max allowed baud rate is 38400.
Now i'm using https://www.pjrc.com/teensy/td_libs_AltSoftSerial.html but there is limitation.

Please could you add the option to choose baud rates lower than 57600 like 38400 and 19200.
I have understood that a low baud rate (e.g. 9600) is not allowed due to the TCP tasks that cannot be stopped.

Could you add a menu to change the connection port, not only 23?
The telnet port 23 can be blocked by routers and gateways in some networks (e.g. a corporate network...)

Thank you
Best Regards
Gio

**Comment by tve** [comment]
Implemented in 2.2beta2
