### ISSUE TITLE
Can add the ability to upload remotely through the server.

### ISSUE THREAD

**Issue by mtrucc** [jeelabs/esp-link#355]
This project is great!
Can add the ability to upload remotely through the server.
Is the server to send a command, esp8266 will be able to automatically download the server-side files and programming Arduino

for example, I am now writing a car anti-theft module, gave my friend, the results module has some BUG, then I need to update remotely.

For example, I have a server iot.server.com.
When esplink is able to connect to the Internet, it starts listening for commands from iot.server.com or sends the IP address to the server so that the server can execute the upload process

I should have esplink keep sending to website (POST)
Then the server can know the IP

I found that I can not upload programs using WAN IP
COM to LAN IP : ok
but com to wan ip : failed

**Comment by uzi18** [comment]
I use for this simple bash script on server.

20.01.2018 12:56 PM "mtrucc" <notifications@github.com> napisał(a):

**Comment by mtrucc** [comment]
@uzi18 No, I mean esp-link can automatically listen for commands from remote servers after networking.
For example, I have a server iot.server.com.
When esplink is able to connect to the Internet, it starts listening for commands from iot.server.com or sends the IP address to the server so that the server can execute the upload process

**Comment by uzi18** [comment]
You can send this IP to server by using ELClient library.

2018-01-20 13:03 GMT+01:00 mtrucc <notifications@github.com>:

**Comment by mtrucc** [comment]
@uzi18 My contact email is mtrucc@gmail.com Can you contact me, I will only use docker to compile the file, but I will not modify the file, I would like to know how to add ELClient library to esplink

**Comment by uzi18** [comment]
You add ELClient to Your Arduino project and use there, i assume esp-link is connected to Arduino.

**Comment by mtrucc** [comment]
@uzi18 This is not good, I expect esp8266 to be more perfect

**Comment by mtrucc** [comment]
@uzi18 I may say incomplete, I mean, expect esp8266 have such a function, so you do not have to write in the Arduino UNO related procedures. Also, esp8266.h will not be used because esplink is affected after using esp-link?

**Comment by uzi18** [comment]
You need to think about esp-link like serial bridge or ethernet card for Arduino :)

**Comment by uzi18** [comment]
With ELClinet lib, You can say to esp-link to connect to one server and send there something (eg. IP)
It is realy simple.

**Comment by mtrucc** [comment]
Yes, you're right, then I should add ELClient to esplink. Not Arduino.

**Comment by mtrucc** [comment]
wow, it's easy for you, but it's hard for me because I only use Arduino IDE to write some very simple programs. Interestingly, before I understood esplink, I turned out to be using the Arduino IDE flash esplink to convert the hex code into hexadecimal and off-line to burn the Arduino. This makes me sad

**Comment by mtrucc** [comment]
@uzi18  Can you teach me? My email has been sent to you.

**Comment by mtrucc** [comment]
I found that I can not upload programs using WAN IP
COM to LAN IP : ok
but com to wan ip : failed

**Comment by mtrucc** [comment]
too long time later..
