### ISSUE TITLE
MQTT Password Character Limit Too Short

### ISSUE THREAD

**Issue by asobey** [jeelabs/esp-link#356]
The Adafruit_MQTT server creates standard AIO Key/Password of 32 characters. I am unable to use that specific MQTT server because of the 31 character limit. Here is the error message I receive:

Error: Value for mqtt-password too long (32 > 31 allowed)

**Comment by uzi18** [comment]
Where did You get this Error - please attach here screenshot

**Comment by asobey** [comment]
When I get home I will attach an image, but in the meantime:

It occurred under the 'REST/MQTT' tab, in the 'Password' Field at the bottom. The error message mentioned above appears at the top of the page.

When I reduce the password by one character to 31 the page allows it.

**Comment by asobey** [comment]
![esp-link_mqtt_password_issue](https://user-images.githubusercontent.com/5262716/35306417-252c977e-0063-11e8-8416-e02d04b577ef.PNG)

**Comment by tve** [comment]
@asobey does uzi18's version fix your issue?

**Comment by asobey** [comment]
I apologize for not being able to check this.  I looked at the code and it appears that it should work, but I am unable to BUILD the .bin files. I will keep trying.

**Comment by uzi18** [comment]
If You want I will attach here my compiled version

2018-01-27 21:05 GMT+01:00 asobey <notifications@github.com>:

**Comment by uzi18** [comment]
[firmware.zip](https://github.com/jeelabs/esp-link/files/1853871/firmware.zip)

Here You are :)

**Comment by vctrvlad** [comment]
Hi!
Nope, that ain't working...

I am now scratching the surface of this IoT thing, and I get the same error message:
![image](https://user-images.githubusercontent.com/37034792/37988305-e0a57e2a-3200-11e8-983f-672f5c2b1cde.png)

This happens even if I flash the user1.bin file provided by uzi18..

I am using this release:
esp-link v3.2.47.alpha.3-gb8605b5-dirty-Lucjan

Should I go earlier?

**Comment by uzi18** [comment]
get my firmware.zip from post above ...

**Comment by vctrvlad** [comment]
Hello uzi18, 

As I mentioned, I have tried it already.
I have flashed user1.bin in the zip provided by you, and same behavior...
Maybe I am doing something wrong?

![image](https://user-images.githubusercontent.com/37034792/37990619-19035b56-3207-11e8-877f-dfcca9311257.png)

Also, please tell me what tools do I need and how to compile this project, I am using a Win10 machine.
I also have Mingw installed.

Thanks for your prompt answer.

P.S. sorry, but not really did a crosscompiling process without an IDE that would handle the makefile and so on... so I would be grateful if you would push a little help

**Comment by asobey** [comment]
I too had trouble with that Zip file, but I did not want to comment yet, as I have not giving the problem enough of a troubleshoot as it deserves.

**Comment by vctrvlad** [comment]
I think the problem is in the following conditional statement:

![image](https://user-images.githubusercontent.com/37034792/37991993-e37cee80-320a-11e8-89d3-c39ae350a8eb.png)

in the file cgi.c

and size of the mqtt_password should remain 32.

**Comment by vctrvlad** [comment]
and maybe there is a hiden problem deeper in the httpd.c file in the function that returns the length of the parameter:

![image](https://user-images.githubusercontent.com/37034792/37992633-918f70c8-320c-11e8-8bbd-95b69d684ffc.png)

?

**Comment by uzi18** [comment]
only problem was not clean rebuild and var must have 65 chars minimum, this firmware is ok:
[firmware.zip](https://github.com/jeelabs/esp-link/files/1853871/firmware.zip)

**Comment by vctrvlad** [comment]
ok, my bad then, I will give it a try...

Later Edit:
It works now, thank you.
Anyway, I am still looking for a minimum info of how to build this :D.

And the next problem would be: 
How do I configure the topic for MQTT in this toy?

Thanks.
