### ISSUE TITLE
Build Instructions Tips/Clarifications

### ISSUE THREAD

**Issue by kd-2020** [jeelabs/esp-link#4]
I just did a fresh install of everything on a Mint 17.1 32bit virtual machine in VirtualBox.

I took a few notes of what I had to do to get it running and thought it would be helpful to other newbies. These steps were omitted in the readme.

I had to install zlib1g-dev:

```
sudo apt-get install zlib1g-dev
```

~~I also had to install esptool:~~
I also had to install python-serial for esptool to work:

```
sudo apt-get install python-serial
```

~~I also went ahead and added the absolute path for esptool.py to the esp-link Makefile.~~

Double check the esp-link makefile for paths, make sure you have the correct path to the esp_iot_sdk (mine was the incorrect version).

Finally, don't forget to make sure that the esp-open-sdk/xtensa-lx106-elf/bin is in the PATH.

[EDIT]
I realize now that esptool should have been installed when I installed esp-open-sdk. Manually installing it probably wasn't necessary, I probably had a PATH issue.

**Comment by tve** [comment]
Thanks for the info, i will incorporate. I now have a set-up that can use esptool.py so i can test it. You've figured this out already, but https://github.com/jeelabs/esp-link/blob/master/BOARDS.md may help someone else reading this.

**Comment by tve** [comment]
I incorporated what I could into the readme 1dfb379
