### ISSUE TITLE
DELETED

### ISSUE THREAD

**Issue by shuaiger** [jeelabs/esp-link#409]
...

**Comment by uzi18** [comment]
after serial flashing, you need to upload user2.bin by OTA

**Comment by shuaiger** [comment]
...

**Comment by uzi18** [comment]
what is Your flash ID?
Please paste here your full esptool command

**Comment by shuaiger** [comment]
...

**Comment by shuaiger** [comment]
...

**Comment by tve** [comment]
TBH I forget the details about 1M+1M flash, but the linking certainly has to be adjusted for it. Is there a specific reason you want to use it?

**Comment by shuaiger** [comment]
..
