### ISSUE TITLE
How to get esp host name in uC?

### ISSUE THREAD

**Issue by PomeloRock** [jeelabs/esp-link#437]
I find GetWifiStatus() but I would like to get esp host name in ELClient in Arduino.

Is there any way?

Thanks.

**Comment by uzi18** [comment]
I think it is imposible now.

**Comment by PomeloRock** [comment]
@uzi18 Thanks!

**Comment by uzi18** [comment]
elclient+esp-link need to be extended, with such feature

**Comment by swilson86** [comment]
Depending on which version of esp-link/el-client you have, it can be done if you are using MQTT. See the notes at https://github.com/jeelabs/esp-link/issues/418

This particular block of code will return the MQTT name which usually is the same as the station name (with exception of slashes which might have to be substituted with a hyphen):

  // Query the MQTT clientid
  Serial.print("MQTT client id : ");
  char *mqtt_clientid = cmd.mqttGetClientId();
  Serial.println(mqtt_clientid);

**Comment by uzi18** [comment]
It's some kind of workaround =)

**Comment by PomeloRock** [comment]
I will try and comment, thanks.

**Comment by PomeloRock** [comment]
error: 'class ELClientCmd' has no member named 'mqttGetClientId'

esp-link-v3.0.14-g963ffbb . Is it the last one, right?

el-client, I don't know where is the version, but I think is the last one too because I downloaded last week.

Any idea? Thanks.

**Comment by swilson86** [comment]
esp-link v3.2.47-g9c6530d

**Comment by PomeloRock** [comment]
oh.. I thought v3.2 was unstable, I will try and comment. Gracias!

**Comment by swilson86** [comment]
I have found it very solid for what I do. It's got some great bug fixes... especially in the area that you are I spoke about. Keep me posted! Ah... I still use the same old El-Client. Hasn't been updated for years.

**Comment by PomeloRock** [comment]
I have flashed v3.2 and is working ok, I have also working OTA with avrdude.

I still need hostname or wifi SSID.

**Comment by swilson86** [comment]
Excellent! The notes on thread 418 on this forum show how it was solved getting the IP address etc. There is example working code there.

**Comment by PomeloRock** [comment]
Thanks for help.

**Comment by uzi18** [comment]
related to #418
