### ISSUE TITLE
sending to ATmeaga328p via avrdude failing 

### ISSUE THREAD

**Issue by notsolowki** [jeelabs/esp-link#447]
i know this may not be related to ESPLINK specifically but i bet people here know more about this issue. i been trying to flash an arduino with avrdude and esplink. using a atmeaga328p the only way i could flash over network is at 57600 baud, which isn't really an issue for me. however the only way to get it to take the hex file is if i use -F to force the file otherwise i get a signature error. it shows my device signature as 0x000000. i am using the optiboot boot loader. then the second issue is if i have anything printing to the serial console from the arduino i have to try to send the hex file over and over again until it will randomly accept it.  the reset pin is wired properly and the sketch it forcefully uploaded is working. not sure whats going wrong.
`
C:\Program Files (x86)\Arduino\hardware\tools\avr\bin>avrdude -p atmega328p -c stk500v1 -P net:10.0.0.110:2323 -b 57600  -U flash:w:hex.hex -D  -F
avrdude: ser_drain(): read error: The parameter is incorrect.

avrdude: ser_drain(): read error: The parameter is incorrect.

avrdude: ser_drain(): read error: The parameter is incorrect.

avrdude: stk500_getsync() attempt 1 of 10: not in sync: resp=0x69

avrdude: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.02s

avrdude: Device signature = 0x000000 (retrying)

Reading | ################################################## | 100% 0.02s

avrdude: Device signature = 0x000000 (retrying)

Reading | ################################################## | 100% 0.02s

avrdude: Device signature = 0x000000
avrdude: Yikes!  Invalid device signature.
avrdude: Expected signature for ATmega328P is 1E 95 0F
avrdude: reading input file "hex.hex"
avrdude: input file hex.hex auto detected as Intel Hex
avrdude: writing flash (1498 bytes):

Writing | ################################################## | 100% 0.88s

avrdude: 1498 bytes of flash written
avrdude: verifying flash memory against hex.hex:
avrdude: load data flash data from input file hex.hex:
avrdude: input file hex.hex auto detected as Intel Hex
avrdude: input file hex.hex contains 1498 bytes
avrdude: reading on-chip flash data:

Reading | ################################################## | 100% 0.78s

avrdude: verifying ...
avrdude: 1498 bytes of flash verified

avrdude: safemode: Fuses OK (E:00, H:00, L:00)

avrdude done.  Thank you.`

**Comment by uzi18** [comment]
could you provide debug log (packets received and sent) from avrdude?
