### ISSUE TITLE
Static ip settings lost after wiflash update.

### ISSUE THREAD

**Issue by bc547** [jeelabs/esp-link#48]
I configured esp-link to use a static ip address instead of DHCP.

After compiling the latest 'master' firmware and uploading it to my ESP-7 via wiflash, the ESP switched back to DHCP and lost the static ip settings after the reboot.

Is this the intended behaviour?

(I'm not yet familiar enough with the code to fix/analyse it myself at this moment, so i report it here)

**Comment by tve** [comment]
No, that's not intended. Grr

**Comment by tve** [comment]
Q: from which version did you upgrade to master from? I had to change the checksum calculation recently, so that would have lost all flash settings.

**Comment by bc547** [comment]
I did upgrade from your precompiled binaries (2.0.beta2) to the master branch code at commit f057a65.

**Comment by tve** [comment]
I double-checked, this is expected. I switched the flash config checksum to a proper crc after beta2. Sorry for the hassle.

**Comment by bc547** [comment]
No problem :-) Thanks for the effort!
