### ISSUE TITLE
Reset µC using curl

### ISSUE THREAD

**Issue by HNeumeier** [jeelabs/esp-link#514]
Hello,
is it possible to reset the attached Microcontroller with a curl command from my automation software, because often the Webinterface is working but no Messages comming from the Serial attached Microcontroller and after Reset uC everything is working again.

**Comment by uzi18** [comment]
Yes it is :)

**Comment by HNeumeier** [comment]
and how.
http://192.168.2.52/console.html  ...................

**Comment by uzi18** [comment]
Try http://192.168.2.52/console/reset

**Comment by HNeumeier** [comment]
thanks for your help,it is working.

**Comment by uzi18** [comment]
It is also possible that problem is somewhere else.

**Comment by uzi18** [comment]
Try my build from issue #513

**Comment by uzi18** [comment]
@HNeumeier did you tried?

**Comment by HNeumeier** [comment]
yes, it is working the command resets the Mikrokontroller, thanks..
