### ISSUE TITLE
[Question] How can disable auto reset microcontroller after tern on esp 01 module??

### ISSUE THREAD

**Issue by hamedrepublic** [jeelabs/esp-link#515]
Hi 
I after connect3.3  voltage to my esp 01for turn on module ,my ardunio uno board has reseted
How can this feature be disabled?

**Comment by uzi18** [comment]
You can add capacitor between RESET and GND

**Comment by hamedrepublic** [comment]
> You can add capacitor between RESET and GND

What  should I use the capacitor with number?
Does adding a capacitor prevent the uno from reset when the sketch is not uploaded?
Because my problem is just resetting the uno when the module ESP-01 is turned on

**Comment by uzi18** [comment]
@hamedmalekii https://www.youtube.com/watch?v=AItW1tfbLTc

**Comment by uzi18** [comment]
@hamedmalekii please describe your configuration and connections esp-uno

**Comment by hamedrepublic** [comment]
> @hamedmalekii please describe your configuration and connections esp-uno

ok i shared  
![arduino-esp-01-program](https://user-images.githubusercontent.com/26657615/106951047-8020c380-6744-11eb-8371-3c808d59eb9b.png)

**Comment by uzi18** [comment]
@hamedmalekii OK try to add 1000uF capacitor on 3v3 and GND line

**Comment by hamedrepublic** [comment]
> @hamedmalekii OK try to add 1000uF capacitor on 3v3 and GND line


I used 10uf capacitor between reset uno line and GPLO0 and my problem solved 
thanks for everyone
