### ISSUE TITLE
How to change UART Baud Rate

### ISSUE THREAD

**Issue by pilumalu** [jeelabs/esp-link#516]
Hello,

first, thanks a lot for the awesome esp-link !!
Please, how can I change the UART baud rate. Is there a hidden menue I didn`t find ?
Would be very helpful to be able to change all serial settings similar to #511 request.
Thanks !

**Comment by ccutrer** [comment]
you can go to http://esp-link/console.html and use the dropdown, or manually set it to an arbitrary rate with http://esp-link/console/baud?rate=X (and http://esp-link/console/fmt?fmt=8N1 etc. for the other serial settings). You'll need to be on a 3.0 release for the latter to work.

**Comment by uzi18** [comment]
Yes you can change serial settings on console subpage

**Comment by uzi18** [comment]
If you need latest 3.0, link is somewhere in issue #513

**Comment by pilumalu** [comment]
Thanks for pointing me to 3.2.47.
Just flashed and baud setting works great now !
Good work !!
