### ISSUE TITLE
flash settings for Wemos D1 Mini Pro?

### ISSUE THREAD

**Issue by smitec11** [jeelabs/esp-link#524]
I'd tried to flash ESP-link to a Wemos D1 mini pro. which has 16M bytes(128M bit),
can someone tell me which settings to use?

I got it working with : 

python "../esptool/esptool.py" --port COM15 --baud 230400 write_flash --flash_freq 80m --flash_mode dio --flash_size 4MB 0x0000 boot_v1.6.bin 0x1000 user1.bin 0x3FC000 esp_init_data_default.bin 0x3FE000 blank.bin

but (off course) the module shows up as an 4MB.

which settings must I use for the 16M Wemos D1 mini pro?

**Comment by uzi18** [comment]
Please provide flash chip id etc. From webserver page

**Comment by smitec11** [comment]
Flash chip ID =  0xEF 0x4018

**Comment by uzi18** [comment]
You can use same as for 32Mbit - 4MBytes
It is normal because espressive api limitations. 
Rest of flash is not used (from 0x400000)

**Comment by smitec11** [comment]
thanks

**Comment by veonua** [comment]
what is the final string form Wemos D1 Mini?
where can I get the tools, the release doesn't have "../esptool/esptool.py"

**Comment by uzi18** [comment]
You need to install it first on your system

**Comment by veonua** [comment]
![image](https://user-images.githubusercontent.com/1540142/189215032-624bbc93-b806-43d6-828c-996f7046a181.png)

at the same moment, I can flash using Arduino IDE and can't connect with 

`python2 "./esptool/esptool.py" --port /dev/ttyUSB0 --baud 230400 write_flash --flash_freq 80m --flash_mode dio --flash_size 4m 0x0000 boot_v1.6.bin 0x1000 user1.bin 0x3FC000 esp_init_data_default.bin 0x3FE000 blank.bin
`

I've tried to close Arduino IDE, another USB port, and reboot. no luck
