### ISSUE TITLE
[Attached here] Download links for released files no longer work (http://s3.voneicken.com)

### ISSUE THREAD

**Issue by rtek1000** [jeelabs/esp-link#549]
https://github.com/jeelabs/esp-link/releases

[Release 3.2.47 alpha](https://github.com/jeelabs/esp-link/releases/tag/v3.2.47.alpha) Pre-release
Warning: some users have trouble getting this release to work. After flashing nothing happens. Please use 3.0.14 instead for now.

Download: http://s3.voneicken.com/esp-link/esp-link-v3.2.47-g9c6530d.tgz

(Attached here)
[esp-link-v3.2.47-g9c6530d.zip](https://github.com/jeelabs/esp-link/files/8792376/esp-link-v3.2.47-g9c6530d.zip)

[Release 3.0.14](https://github.com/jeelabs/esp-link/releases/tag/V3.0.14) [Latest](https://github.com/jeelabs/esp-link/releases/latest)
Version v3.0 includes many bug fixes and several improvements over v2.2.3. v3.0.14 was released as an alpha Dec 16, 2016 and promoted to stable Jun 17, 2017.

Download: http://s3.voneicken.com/esp-link/esp-link-v3.0.14-g963ffbb.tgz

(Attached here)
[esp-link-v3.0.14-g963ffbb.zip](https://github.com/jeelabs/esp-link/files/8792377/esp-link-v3.0.14-g963ffbb.zip)

**Comment by rapi3** [comment]
thank you
