### ISSUE TITLE
esp-link firmware is not detecting available wi-fi networks while scanning in AP+STA mode but available networks are shown in the debug log of esp-link

### ISSUE THREAD

**Issue by CRSREE** [jeelabs/esp-link#554]
Good day,

I am using esp12E module with esp-link firmware flashed on it. Initially it will act as a AP point and I can connect to the esp-link network. When I try to configure the esp module to one of the available networks, while scanning in AP+STA mode esp-link does not shows any available networks. The scanning is going on for a long loop. But in the esp-link debug log , I can see all the available networks but it is not showing in the GUI of esp-link.
![scanning1](https://user-images.githubusercontent.com/114198471/192192396-b2260f90-9928-49e7-8a77-40f225009733.PNG)

This is happening only in a particular location. When I tried in a different location the same esp module can detect the available networks while scanning in AP+STA mode and shows on the GUI. I know it is something related to the networks in the particular area, but how can I fix this to get all the available networks shown on the GUI of esp-link while scanning in AP+STA mode ?

Thanks

**Comment by CRSREE** [comment]
Similiar to #370

**Comment by uzi18** [comment]
@CRSREE please provide debug log and json response from esp.
