### ISSUE TITLE
wlan bridge/repeater

### ISSUE THREAD

**Issue by Vonderhecke** [jeelabs/esp-link#577]
Hello,
I have esp-link running in AP-STA mode via station, WAN can also be reached and a gateway (for static IP) is also specified below under "Special Settings". However, a client logged in via the Soft AP does not have Internet access. It can access both the 192.168.4.1 and the station IP, for me a static one. So on the esp-link web server and Telnet but not on the Internet. Would it be possible?
Many thanks for the help.

**Comment by uzi18** [comment]
Don't get it, what do you mean by "not on internet"?

**Comment by Vonderhecke** [comment]
there is no connection to the WAN

**Comment by uzi18** [comment]
Yes, AP mode means only connection to ESP to configure it (or local connection). It will not forward packets to WAN as router does.

**Comment by Vonderhecke** [comment]
It's a shame, but it was just an idea that he could have expanded the WiFi a little in addition to the actual tasks.

**Comment by uzi18** [comment]
Not sure if it is possible, should dig some information from IDF documentation.
