### ISSUE TITLE
mdns

### ISSUE THREAD

**Issue by gryor** [jeelabs/esp-link#62]
Is it possible to use mdns with esp-link?
What I mean is something like Avahi or Bonjour type broadcasting of own host name on the local network.
This way the esp module could be found on the network by it's host name: esp-link.local.
As these names must be unique, it would also be nice if the module automatically appended a number to the name: esp-link3.local.

**Comment by tve** [comment]
Very rough support for mDNS added in v2.1.beta3. I'm not happy with it yet, need to test more... But it's coming... :-)
