### ISSUE TITLE
Error compiling " expected '_Bool *' but argument is of type 'uint8_t *'"

### ISSUE THREAD

**Issue by arjenhiemstra** [jeelabs/esp-link#75]
I get the following message(s), any idea why?

esp-link/cgimqtt.c:88:7: error: passing argument 3 of 'getBoolArg' from incompatible pointer type [-Werror]
       &flashConfig.mqtt_clean_session);
       ^
In file included from esp-link/cgimqtt.c:4:0:
esp-link/cgi.h:21:8: note: expected '_Bool *' but argument is of type 'uint8_t *'

**Comment by tve** [comment]
Looks like you're using a different compiler than I do?

```
$ xtensa-lx106-elf-gcc --version
xtensa-lx106-elf-gcc (crosstool-NG 1.20.0) 4.8.2
```

**Comment by arjenhiemstra** [comment]
vagrant@esp8266:~/dev/test-esp-link/esp-link$ xtensa-lx106-elf-gcc --version
xtensa-lx106-elf-gcc (crosstool-NG 1.20.0) 4.8.2

Looks the same

**Comment by arjenhiemstra** [comment]
Ok, changing the following in config.h 
uint8_t  slip_enable, [...]_session;  
to
bool  slip_enable, [...]_session;    

fixed the error

**Comment by stakinnovations** [comment]
I also had to change these:

  bool      syslog_filter;                      // min. severity
  uint8_t  syslog_showtick,              // show system tick (µs)
              syslog_showdate;             // populate SYSLOG date field
  bool     mdns_enable;

**Comment by deece** [comment]
This should be fixed by pull request 134
