### ISSUE TITLE
Add Wifi CHAP Authentication

### ISSUE THREAD

**Issue by davekelly63** [jeelabs/esp-link#79]
Is there a way to authenticate the wifi connection?

My work wifi is more secure, and requires the initial wifi password to connect, but also a username and password to connect to the network.

Currently looking at the log every few seconds it does a reconnect, there are some state messages, then disconnects from Wifi with reason unspecified.

**Comment by brunnels** [comment]
you probably need CHAP authentication which isn't currently supported.

**Comment by tve** [comment]
This is a valid request, someone would have to implement CHAP or similar...

**Comment by tve** [comment]
closing 'cause nothing has moved here in a very long time.
