### ISSUE TITLE
Port 23 hangs

### ISSUE THREAD

**Issue by SpaceCadet-Code** [jeelabs/esp-link#81]
Hey, I was using port 23 through a php script that opens a socket and it worked for a while but now the port is not accepting connections. Maybe add a way to reset the port via esp webpage.

**Comment by tve** [comment]
Mhh, can you describe this further? I've never seen anything like this.

**Comment by SpaceCadet-Code** [comment]
Programming  issue not the firmware sorry. My php script hung the port open.
