### ISSUE TITLE
Looses flash

### ISSUE THREAD

**Issue by SpaceCadet-Code** [jeelabs/esp-link#82]
Hey, I have an issue where if I disconnect the esp from power it looses flash and the wifi connection shows "hidden network".

**Comment by tve** [comment]
Which version are you using? What size flash chip does your esp8266 module have? How did you flash it or what is it saying on the home page about the flash size and flash chip? The last time someone had a similar sounding problem they had not passed the right -ff / -fs parameters to esptool.py when flashing.

**Comment by SpaceCadet-Code** [comment]
esp-link v2.1.beta6. 4MB:512/512. Using NODEMCU Firmware Programmer.

**Comment by SpaceCadet-Code** [comment]
Re flashed with Linux and the esptool and it seems to work. Any ideas on how to make it work in windows?

**Comment by tve** [comment]
Use esptool.py under windows, or use the official Espressif flasher. I think the nodemcu flasher doesn't allow you to set the flash size correctly.
