### ISSUE TITLE
Permanently disable uart hard code

### ISSUE THREAD

**Issue by SpaceCadet-Code** [jeelabs/esp-link#83]
I was wondering about was permanently disabling UART debugging as in hard code to disable it. It becomes problematic at times.

**Comment by tve** [comment]
If you set debug log to OFF on the DebugLog page, then it's off. The setting is saved in flash. Please reopen if this doesn't work for you.

**Comment by SpaceCadet-Code** [comment]
Yes that works but I would like to know is there a way though to disable this before flashing.
