### ISSUE TITLE
RX pull-up broken in GUI

### ISSUE THREAD

**Issue by philstonio** [jeelabs/esp-link#90]
Checking "RX pull-up" and clicking change in to GUI actually submits...

```
POST /pins?reset=12&isp=14&conn=0&ser=2&swap=0&rxpup=0
```

rather than

```
POST /pins?reset=12&isp=14&conn=0&ser=2&swap=0&rxpup=1
```

I suspect .selected should be .checked at... https://github.com/jeelabs/esp-link/blob/master/html/ui.js#L476

I also noticed that the GUI always shows "RX pull-up" as checked because it is hard coded to 1 here...
https://github.com/jeelabs/esp-link/blob/master/esp-link/cgipins.c#L37

**Comment by tve** [comment]
This is fixed in v2.2.beta1 :-)
