### ISSUE TITLE
mbed-compatible board

### ISSUE THREAD

**Issue by andriyadi** [jeelabs/esp-link#92]
Just wondering, can this project be used to flash/update firmware mbed-compatible boards?
Please advice.
Thanks.

**Comment by tve** [comment]
I believe "mbed compatible board" is too vague a description. esp-link is a serial-wifi bridge, so if you can program your ARM processor over its UART then you can most likely program it using esp-link. For example, I know it works with NXP's LPC series. Some STM32 processors can also be programmed using the UART, but I have not tried. Esp-link is not an ST-Link programmer (which uses JTAG or SWD).

**Comment by andriyadi** [comment]
@tve apology for late response.
I'm using STM32 Nucleo F401RE and code for it using mbed, instead of its native framework. I'll try it at the soonest.
Thanks.

**Comment by ShaneKirkbride** [comment]
@andriyadi do you have a link to how you are programming the STM32 (I have a Nucleo F446RE) I'm trying to do just this but I don't want to reinvent the wheel. :-)

**Comment by tve** [comment]
Closing ticket: I don't have an answer and there's nothing actionable for me. Feel free to reopen.
