### ISSUE TITLE
How to get the MAC Address.

### ISSUE THREAD

**Issue by astronomer80** [jeelabs/esp-link#96]
Hi, is it possible to get the MAC address of the ESP8266 via UART? Thanks.

**Comment by adrianocos** [comment]
Uora u facemu, ci penso io ... (only Sicilian guys)

**Comment by walduino** [comment]
I kinda had the same request from an EL-client standpoint
IP/MAC adress
Hostname

would be helpful

https://github.com/jeelabs/el-client/issues/15

**Comment by dannybackx** [comment]
Sample implementation submitted for review, see https://github.com/jeelabs/esp-link/pull/206 .

**Comment by tve** [comment]
Merged
