### ISSUE TITLE
Controll GPIO over a seperate TCP Port an the WebIf

### ISSUE THREAD

**Issue by stockklauser** [jeelabs/esp-link#99]
Hello, 

if it possible i to controll the GPIO Pins over the Webinterface not only for Programming, i have seen two possible ways to use it for the most applications: 

-> A Seperatre TCP Port like 2333 to send Commands like:
         -> Set GPIO Level (Low / High)
         -> Set GPIO Direction
         -> Get GPIO State (for Inputs and Outputs)
-> A Webinterface Page to Controll and Configure the Ports
        -> Same like TCP Commands

This woud be a nice Feature to use the Pins after the Programming to Conroll more Features #

**Comment by dvv** [comment]
+1

**Comment by tve** [comment]
closing 'cause nothing has moved here in a very long time.
